<a href="https://colab.research.google.com/github/Angelgupta13/Deep-learning-/blob/main/basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
 tensor =torch.tensor([1,2,3])
 tensor+10

tensor([11, 12, 13])

In [ ]:
x=torch.arange(0,11,1)
torch.min(x)

tensor(0)

In [ ]:
x=torch.arange(1.,10.)
x,x.shape,x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
x=x.reshape(9,1)
x,x.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 2)