<a href="https://colab.research.google.com/github/Angelgupta13/Deep-learning-/blob/main/Random_seed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
random_seed=2
torch.manual_seed(random_seed)
random_A=torch.rand(3,4)
random_seed=2
torch.manual_seed(random_seed)
random_B=torch.rand(3,4)
print(random_A)
print(random_B)
print(random_A==random_B)

tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])
tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
device="cuda" if torch.cuda.is_available() else "hi"
device

'cuda'

In [ ]:
random_seed=0
torch.manual_seed(random_seed)
a=torch.tensor([1,2,3,])
a,a.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
random_seed=0
torch.manual_seed(random_seed)
b=torch.tensor([1,2,3],device=device)
b,b.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
b.cpu().numpy()

array([1, 2, 3])

In [ ]:
random_seed=0
torch.manual_seed(random_seed)
a=torch.rand(7,7)
a

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
random_seed=0
torch.manual_seed(random_seed)
b=torch.rand(7,7)


In [ ]:
print(a==b)

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])


In [ ]:
device="1234" if torch.cuda.is_available else "na"
device

'1234'

In [ ]:
device="cuda" if torch.cuda.is_available() else "hi"
device
random_seed=1234
torch.manual_seed(random_seed)
a=torch.rand((2,3),device=device)
a


tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [ ]:
random_seed=1234
torch.manual_seed(random_seed)
b=torch.rand((2,3),device=device)
b

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [ ]:
C=torch.matmul(a,b.T)
torch.min(C),torch.max(C)

(tensor(0.8358, device='cuda:0'), tensor(1.4578, device='cuda:0'))

In [ ]:
ab=torch.rand(1,1,1,10)
bc=torch.squeeze(ab)
bc.shape,bc,ab

(torch.Size([10]),
 tensor([0.3112, 0.7091, 0.1775, 0.4443, 0.1230, 0.9638, 0.7695, 0.0378, 0.2239,
         0.6772]),
 tensor([[[[0.3112, 0.7091, 0.1775, 0.4443, 0.1230, 0.9638, 0.7695, 0.0378,
            0.2239, 0.6772]]]]))